export const sessionTemplates = [
  {
    id: 'school-assembly',
    label: 'School Assembly',
    description: 'Classic draw for school events. Names mode, 3 prizes, winners removed after each draw.',
    settings: {
      title: 'School Assembly Lucky Draw',
      subtitle: 'Congratulations to all winners!',
      drawMode: 'names',
      operationMode: 'standard',
      prizes: [
        { id: 1, name: '3rd Prize' },
        { id: 2, name: '2nd Prize' },
        { id: 3, name: '1st Prize' },
      ],
      winnersPerPrize: 1,
      winnerEligibilityMode: 'remove',
      noRepeatAcrossPrizes: true,
      theme: 'Corporate Blue',
    },
  },
  {
    id: 'raffle-draw',
    label: 'Raffle Draw',
    description: 'Traditional numbered raffle. 5-tier prize structure from Consolation to Grand Prize.',
    settings: {
      title: 'Grand Raffle Draw',
      subtitle: 'Your lucky number could be next!',
      drawMode: 'numbers',
      operationMode: 'standard',
      prizes: [
        { id: 1, name: 'Consolation Prize' },
        { id: 2, name: '3rd Prize' },
        { id: 3, name: '2nd Prize' },
        { id: 4, name: '1st Prize' },
        { id: 5, name: 'Grand Prize' },
      ],
      winnersPerPrize: 1,
      winnerEligibilityMode: 'remove',
      noRepeatAcrossPrizes: true,
      theme: 'Event Night',
    },
  },
  {
    id: 'classroom-picker',
    label: 'Classroom Random Picker',
    description: 'Pick a random student to answer. Winners stay in pool for repeated picks.',
    settings: {
      title: 'Random Student Picker',
      subtitle: 'Who will answer next?',
      drawMode: 'names',
      operationMode: 'standard',
      prizes: [
        { id: 1, name: 'Question 1' },
        { id: 2, name: 'Question 2' },
        { id: 3, name: 'Question 3' },
        { id: 4, name: 'Question 4' },
        { id: 5, name: 'Question 5' },
      ],
      winnersPerPrize: 1,
      winnerEligibilityMode: 'keep',
      noRepeatAcrossPrizes: false,
      theme: 'Carnival Red',
    },
  },
  {
    id: 'student-council',
    label: 'Student Council Selection',
    description: 'Randomly assign council roles (President, VP, Secretary, Treasurer) to students.',
    settings: {
      title: 'Student Council Selection',
      subtitle: 'Randomly assigning roles for this term',
      drawMode: 'names',
      operationMode: 'role-selector',
      roleConfigText: 'President:1\nVice President:1\nSecretary:1\nTreasurer:1',
      allowMultipleRoles: false,
      prizes: [{ id: 1, name: 'Council Roles' }],
      winnersPerPrize: 1,
      winnerEligibilityMode: 'remove',
      noRepeatAcrossPrizes: true,
      theme: 'Corporate Blue',
    },
  },
  {
    id: 'team-divider',
    label: 'Team Divider Event',
    description: 'Divide all participants into 4 balanced teams randomly.',
    settings: {
      title: 'Team Divider',
      subtitle: 'Forming balanced teams',
      drawMode: 'names',
      operationMode: 'team-divider',
      teamCount: 4,
      prizes: [{ id: 1, name: 'Team Assignment' }],
      winnersPerPrize: 1,
      winnerEligibilityMode: 'remove',
      noRepeatAcrossPrizes: false,
      theme: 'Neon Party',
    },
  },
];
