export const themes = {
  'Event Night': {
    '--bg-color': '#111827',
    '--text-color': '#ffffff',
    '--text-muted': '#9ca3af',
    '--panel-bg': 'rgba(17, 24, 39, 0.8)',
    '--panel-border': '#374151',
    '--input-bg': '#374151',
    '--display-bg': '#000000',
    '--display-border': '#374151',
    '--display-text': '#06b6d4',
    '--display-shadow': 'rgba(6, 182, 212, 0.7)',
    '--title-color': '#facc15',
    '--button-primary-bg': '#3b82f6',
    '--button-action-bg': '#f59e0b',
    '--confetti-colors': ['#f44336', '#e91e63', '#9c27b0', '#673ab7', '#3f51b5', '#2196f3', '#03a9f4', '#00bcd4', '#009688', '#4caf50', '#8bc34a', '#cddc39', '#ffeb3b', '#ffc107', '#ff9800'],
  },
  'Corporate Blue': {
    '--bg-color': '#f0f4f8', '--text-color': '#1e293b', '--text-muted': '#475569', '--panel-bg': 'rgba(255, 255, 255, 0.9)', '--panel-border': '#cbd5e1', '--input-bg': '#ffffff', '--display-bg': '#0f172a', '--display-border': '#d4af37', '--display-text': '#ffffff', '--display-shadow': 'rgba(212, 175, 55, 0.5)', '--title-color': '#0f172a', '--button-primary-bg': '#0f172a', '--button-action-bg': '#d4af37', '--confetti-colors': ['#0f172a', '#d4af37', '#ffffff', '#94a3b8'],
  },
  'Carnival Red': {
    '--bg-color': '#fffbeb', '--text-color': '#7f1d1d', '--text-muted': '#b91c1c', '--panel-bg': 'rgba(254, 252, 232, 0.9)', '--panel-border': '#fca5a5', '--input-bg': '#ffffff', '--display-bg': '#dc2626', '--display-border': '#ffffff', '--display-text': '#ffffff', '--display-shadow': 'rgba(255, 255, 255, 0.7)', '--title-color': '#dc2626', '--button-primary-bg': '#1d4ed8', '--button-action-bg': '#dc2626', '--confetti-colors': ['#dc2626', '#1d4ed8', '#ffffff', '#fef08a'],
  },
  'Neon Party': {
    '--bg-color': '#000000', '--text-color': '#f5f5f5', '--text-muted': '#a3a3a3', '--panel-bg': 'rgba(23, 23, 23, 0.8)', '--panel-border': '#ec4899', '--input-bg': '#171717', '--display-bg': '#000000', '--display-border': '#a855f7', '--display-text': '#34d399', '--display-shadow': 'rgba(52, 211, 153, 0.7)', '--title-color': '#ec4899', '--button-primary-bg': '#a855f7', '--button-action-bg': '#ec4899', '--confetti-colors': ['#ec4899', '#a855f7', '#34d399', '#facc15', '#0ea5e9'],
  },
};

export const fonts = {
  'Sans Serif': "Inter, 'Noto Sans Myanmar', 'Myanmar Text', 'Padauk', 'Tharlon', 'Pyidaungsu', sans-serif",
  Serif: "'Noto Serif Myanmar', 'Times New Roman', serif",
  Monospace: "'Roboto Mono', 'Noto Sans Myanmar', 'Myanmar Text', monospace",
  Montserrat: "Montserrat, 'Noto Sans Myanmar', 'Myanmar Text', sans-serif",
  'Playfair Display': "'Playfair Display', 'Noto Serif Myanmar', serif",
  Roboto: "Roboto, 'Noto Sans Myanmar', 'Myanmar Text', sans-serif",
  Lobster: "Lobster, 'Noto Sans Myanmar', 'Myanmar Text', cursive",
  'Burmese Sans (Myanmar)': "'Noto Sans Myanmar', 'Myanmar Text', 'Padauk', 'Tharlon', 'Pyidaungsu', sans-serif",
  'Burmese Serif (Myanmar)': "'Noto Serif Myanmar', 'Myanmar Text', serif",
  'Mon Unicode Safe': "'Noto Sans Myanmar', 'Myanmar Text', 'Padauk', 'Tharlon', 'Pyidaungsu', sans-serif",
  'Sai K2 Handwriting': "'Sai K2 Handwriting', 'Noto Sans Myanmar', 'Myanmar Text', sans-serif",
  'Z01 Umoe002': "'Z01 Umoe002', 'Noto Sans Myanmar', 'Myanmar Text', sans-serif",
  'Z02 Typewriter': "'Z02 Typewriter', 'Noto Sans Myanmar', 'Myanmar Text', monospace",
  'Z03 Press': "'Z03 Press', 'Noto Sans Myanmar', 'Myanmar Text', sans-serif",
  'Z06 Walone': "'Z06 Walone', 'Noto Sans Myanmar', 'Myanmar Text', sans-serif",
  'Z07 Modern': "'Z07 Modern', 'Noto Sans Myanmar', 'Myanmar Text', sans-serif",
  'Z08 Strong': "'Z08 Strong', 'Noto Sans Myanmar', 'Myanmar Text', sans-serif",
  'Z09 Lat Yay Sat': "'Z09 Lat Yay Sat', 'Noto Sans Myanmar', 'Myanmar Text', sans-serif",
  'Z10 Cartoon': "'Z10 Cartoon', 'Noto Sans Myanmar', 'Myanmar Text', sans-serif",
  'Z11 Myan Sans': "'Z11 Myan Sans', 'Noto Sans Myanmar', 'Myanmar Text', sans-serif",
  'Z12 Ahlwan Cafe': "'Z12 Ahlwan Cafe', 'Noto Sans Myanmar', 'Myanmar Text', sans-serif",
  'Z14 Irrawaddy': "'Z14 Irrawaddy', 'Noto Sans Myanmar', 'Myanmar Text', sans-serif",
  'Z15 Korea': "'Z15 Korea', 'Noto Sans Myanmar', 'Myanmar Text', sans-serif",
  'Z16 Sahara': "'Z16 Sahara', 'Noto Sans Myanmar', 'Myanmar Text', sans-serif",
  'Z17 Strength': "'Z17 Strength', 'Noto Sans Myanmar', 'Myanmar Text', sans-serif",
  'Z18 Gabar': "'Z18 Gabar', 'Noto Sans Myanmar', 'Myanmar Text', sans-serif",
  'Z20 Khit Haungg': "'Z20 Khit Haungg', 'Noto Sans Myanmar', 'Myanmar Text', sans-serif",
  'Z22 Gantgaw Lann': "'Z22 Gantgaw Lann', 'Noto Sans Myanmar', 'Myanmar Text', sans-serif",
};
